// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6m0k-rhhwXRxe6ANiT96MMgOTgnLpSA',
    appId: '1:600538180915:web:70255b52b445b5070e2246',
    messagingSenderId: '600538180915',
    projectId: 'rentify-b874e',
    authDomain: 'rentify-b874e.firebaseapp.com',
    storageBucket: 'rentify-b874e.firebasestorage.app',
    measurementId: 'G-YSJRVM6ET1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcOTEfNoY-SPPqIrLqIDDzOvS8KgqxfUg',
    appId: '1:600538180915:android:a977037569f6f9a30e2246',
    messagingSenderId: '600538180915',
    projectId: 'rentify-b874e',
    storageBucket: 'rentify-b874e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq4mjszfF2vwkWIRx2MI39R3ka78R-pzE',
    appId: '1:600538180915:ios:4fcf1b659ef4b59d0e2246',
    messagingSenderId: '600538180915',
    projectId: 'rentify-b874e',
    storageBucket: 'rentify-b874e.firebasestorage.app',
    iosBundleId: 'com.rentify.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq4mjszfF2vwkWIRx2MI39R3ka78R-pzE',
    appId: '1:600538180915:ios:4fcf1b659ef4b59d0e2246',
    messagingSenderId: '600538180915',
    projectId: 'rentify-b874e',
    storageBucket: 'rentify-b874e.firebasestorage.app',
    iosBundleId: 'com.rentify.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG6m0k-rhhwXRxe6ANiT96MMgOTgnLpSA',
    appId: '1:600538180915:web:0f521537ea91815a0e2246',
    messagingSenderId: '600538180915',
    projectId: 'rentify-b874e',
    authDomain: 'rentify-b874e.firebaseapp.com',
    storageBucket: 'rentify-b874e.firebasestorage.app',
    measurementId: 'G-TJC0YVYMDG',
  );
}
